import React,{memo,useEffect,useMemo,useRef,useState} from 'react'
import {AnimatePresence,animate,motion,useMotionValue,useReducedMotion,useTransform,type Transition} from 'motion/react'
import {cn} from '../../lib/utils'
const LINE=1.5, FACES=[0,1,2,3,4,5,6,7,8,9], WHEEL=[...FACES,0], EASE=[.22,1,.36,1] as const
const FADE='linear-gradient(to bottom,rgba(0,0,0,0) 0%,rgba(0,0,0,.06) 5.5%,rgba(0,0,0,.5) 11%,rgba(0,0,0,.94) 16.5%,#000 22%,#000 78%,rgba(0,0,0,.94) 83.5%,rgba(0,0,0,.5) 89%,rgba(0,0,0,.06) 94.5%,rgba(0,0,0,0) 100%)';
const spring=(duration:number):Transition=>({type:'spring',visualDuration:duration,bounce:.18});const mod=(n:number,m:number)=>((n%m)+m)%m
const SIZER=FACES.map(face=><span key={face} aria-hidden className="invisible [grid-area:1/1]">{face}</span>);const STACK=WHEEL.map((face,i)=><span key={i} className="flex items-center justify-center" style={{height:`${LINE}em`}}>{face}</span>)
function useWheel(from:number,digit:number,dir:number,duration:number,reduced:boolean){const pos=useMotionValue(from),goal=useRef(from),heading=useRef(dir);useEffect(()=>{heading.current=dir},[dir]);useEffect(()=>{if(reduced){goal.current=digit;pos.set(digit);return}if(mod(goal.current,10)!==digit){const at=pos.get();goal.current=heading.current<0?at-mod(at-digit,10):at+mod(digit-at,10)}const roll=animate(pos,goal.current,spring(duration));return()=>roll.stop()},[digit,duration,reduced,pos]);return useTransform(pos,p=>`${(-mod(p,10)*100)/WHEEL.length}%`)}
function Digit({digit,from,dir,duration,reduced}:{digit:number;from:number;dir:number;duration:number;reduced:boolean}){const y=useWheel(from,digit,dir,duration,reduced);return <motion.span className="counter-digit" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span className="counter-sizer">{SIZER}</span><motion.span style={{y}} className="absolute inset-x-0 top-0">{STACK}</motion.span></motion.span>}
export default function AnimatedCounter({value,decimals=0,duration=.6,padStart=1,separator=',',decimalSeparator='.',grouping='western',prefix,suffix,className,...props}:React.ComponentProps<'span'> & {value:number;decimals?:number;duration?:number;padStart?:number;separator?:string;decimalSeparator?:string;grouping?:'western'|'indian';prefix?:React.ReactNode;suffix?:React.ReactNode}){const reduced=useReducedMotion()??false;const amount=Number.isFinite(value)?value:0;const places=Math.min(15,Math.max(0,Math.trunc(decimals)));const scaled=Math.min(Number.MAX_SAFE_INTEGER,Math.round(Math.abs(amount)*10**places));const raw=String(scaled).padStart(Math.max(String(scaled).length,places+padStart),'0');let whole=raw.slice(0,raw.length-places)||'0';if(separator)whole=grouping==='indian'?(()=>{const head=whole.slice(0,-3);return head?`${head.replace(/\B(?=(\d{2})+(?!\d))/g,separator)}${separator}${whole.slice(-3)}`:whole})():whole.replace(/\B(?=(\d{3})+(?!\d))/g,separator);const chars=places?`${whole}${decimalSeparator}${raw.slice(-places)}`:whole;const [prev,setPrev]=useState(amount);const [dir,setDir]=useState(1);if(prev!==amount){setDir(amount>=prev?1:-1);setPrev(amount)}const cells=chars.split('');const digitCount=cells.filter(c=>/[0-9]/.test(c)).length;const seed=useMemo(()=>{const s:number[]=[];let i=0;for(const c of cells)if(/[0-9]/.test(c))s[i++]=Number(c);return s},[chars]);return <span className={cn('inline-flex items-center tabular-nums',className)} {...props}>{prefix}<span className="sr-only">{amount<0&&'-'}{chars}</span><span aria-hidden className="inline-flex items-center">{amount<0&&'-'}<AnimatePresence mode="popLayout" initial={false}>{cells.map((c,i)=>/[0-9]/.test(c)?<Digit key={`d-${digitCount-i}`} digit={Number(c)} from={seed[i]??0} dir={dir} duration={reduced?0:duration} reduced={reduced}/>:<motion.span key={`m-${i}`} className="counter-mark" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{c}</motion.span>)}</AnimatePresence></span>{suffix}</span>}
