import React, { useEffect, useRef } from 'react'
import { cn } from '../../lib/utils'

export type FluidOrbProps = React.ComponentProps<'div'> & { size?: number; color?: string }
const VERT = `attribute vec2 a_pos; void main(){ gl_Position=vec4(a_pos,0.0,1.0); }`
const FRAG = `precision mediump float; uniform vec2 u_resolution; uniform float u_time; uniform vec3 u_color;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);} 
float noise(vec2 p){vec2 i=floor(p),f=fract(p);vec2 u=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),u.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),u.x),u.y);} 
float fbm(vec2 p){float v=0.,a=.6;for(int i=0;i<3;i++){v+=a*noise(p);p*=2.;a*=.5;}return v;}
void main(){vec2 uv=gl_FragCoord.xy/u_resolution.xy;float t=u_time*.22;vec2 drift=vec2(sin(t)+.6*sin(t*1.7+1.3),cos(t*.8)+.6*cos(t*1.3+2.1));vec2 p=vec2(uv.x*1.8,uv.y)+drift*.7;vec2 q=vec2(fbm(p+drift),fbm(p+vec2(3.2,1.5)-drift));float f=fbm(p+1.2*q);float g=clamp(1.-uv.y,0.,1.);float anchor=smoothstep(0.,.3,uv.y);float shade=clamp(g+(f-.5)*.8*anchor,0.,1.);vec3 white=vec3(.99,1.,1.),light=mix(white,u_color,.5),dark=u_color,col=white;col=mix(col,light,smoothstep(.28,.52,shade));col=mix(col,dark,smoothstep(.58,.88,shade));float edge=smoothstep(.5,.49,distance(uv,vec2(.5)));gl_FragColor=vec4(col*edge,edge);}`
function rgb(hex:string):[number,number,number]{let h=hex.replace('#','').trim();if(h.length===3)h=h.split('').map(x=>x+x).join('');const n=parseInt(h,16);return h.length!==6||Number.isNaN(n)?[.1,.45,.95]:[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255]}
function compile(gl:WebGLRenderingContext,type:number,src:string){const s=gl.createShader(type);if(!s)return null;gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){console.error(gl.getShaderInfoLog(s));gl.deleteShader(s);return null}return s}
export default function FluidOrb({size=240,color='#6E5BFF',className,style,...props}:FluidOrbProps){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const gl=c.getContext('webgl',{antialias:true,alpha:true});if(!gl)return;const p=gl.createProgram(),v=compile(gl,gl.VERTEX_SHADER,VERT),f=compile(gl,gl.FRAGMENT_SHADER,FRAG);if(!p||!v||!f)return;gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))return;gl.useProgram(p);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(p,'a_pos');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(p,'u_resolution'),ut=gl.getUniformLocation(p,'u_time'),uc=gl.getUniformLocation(p,'u_color');gl.uniform3f(uc,...rgb(color));const dpr=Math.min(devicePixelRatio||1,2),px=Math.round(size*dpr);c.width=c.height=px;gl.viewport(0,0,px,px);gl.uniform2f(ur,px,px);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,start=performance.now();let raf=0;const render=(now:number)=>{gl.uniform1f(ut,reduce?0:(now-start)/1000);gl.drawArrays(gl.TRIANGLES,0,6);if(!reduce)raf=requestAnimationFrame(render)};render(start);return()=>{cancelAnimationFrame(raf);gl.deleteProgram(p);gl.deleteShader(v);gl.deleteShader(f);gl.deleteBuffer(b)}},[size,color]);return <div className={cn('relative overflow-hidden rounded-full',className)} style={{width:size,height:size,...style}} {...props}><canvas ref={ref} className="h-full w-full" aria-hidden/></div>}
