import React,{useEffect,useRef,useSyncExternalStore} from 'react'
import {cn} from '../../lib/utils'
export type MatrixOrbState='idle'|'listening'|'thinking'
const TAU=Math.PI*2,STATES:MatrixOrbState[]=['idle','listening','thinking'];const SCALE={idle:.88,listening:1,thinking:.92};const ORBITERS=[{radius:.62,speed:2.2,phase:0,spread:.42},{radius:.4,speed:-1.7,phase:2.1,spread:.36},{radius:.8,speed:1.15,phase:4,spread:.34}]
function envelope(t:number){const slow=.5+.5*Math.sin(t*.62+.4),fast=.5+.5*Math.sin(t*1.9+1.1);return .22+.78*(.45+.55*slow)*fast}
function intensity(state:MatrixOrbState,d:number,nx:number,ny:number,t:number,a:number){if(state==='listening'){const ripple=.5+.5*Math.sin(d*4.2-t*3);return .32+a*(.34+.38*ripple)}if(state==='thinking'){let heat=0;for(const o of ORBITERS){const x=t*o.speed+o.phase,dx=nx-Math.cos(x)*o.radius,dy=ny-Math.sin(x)*o.radius;heat+=Math.exp(-(dx*dx+dy*dy)/(o.spread*o.spread))}return .26+.8*Math.min(1,heat)}return .62+.12*Math.sin(t*1.05-d*2.4)}
function subscribe(cb:()=>void){window.addEventListener('resize',cb);return()=>window.removeEventListener('resize',cb)}
function useDpr(){return useSyncExternalStore(subscribe,()=>Math.min(devicePixelRatio||1,4),()=>1)}
export default function MatrixOrb({state='idle',level,size=240,color='#6E5BFF',dots=11,labels,className,...props}:React.ComponentProps<'div'> & {state?:MatrixOrbState;level?:number;size?:number;color?:string;dots?:number;labels?:Partial<Record<MatrixOrbState,string>>}){const ref=useRef<HTMLCanvasElement>(null),stateRef=useRef(state),levelRef=useRef(level),dpr=useDpr();useEffect(()=>{stateRef.current=state;levelRef.current=level},[state,level]);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!c||!ctx)return;const buffer=Math.round(size*dpr);c.width=c.height=buffer;ctx.scale(buffer/size,buffer/size);ctx.fillStyle=color;const grid=Math.max(3,Math.round(dots)),half=(grid-1)/2,spacing=size*.74/(grid-1),maxR=spacing*.6,center=size/2,weights={idle:0,listening:0,thinking:0} as Record<MatrixOrbState,number>;weights[stateRef.current]=1;const levelAt=(t:number)=>{const v=levelRef.current;return v===undefined||!Number.isFinite(v)?envelope(t):Math.min(1,Math.max(0,v))};const draw=(t:number,a:number,scale:number)=>{ctx.clearRect(0,0,size,size);for(let iy=0;iy<grid;iy++)for(let ix=0;ix<grid;ix++){const nx=(ix-half)/half,ny=(iy-half)/half,d=Math.hypot(nx,ny);if(d>1.12)continue;let blend=0;for(const s of STATES)blend+=weights[s]*intensity(s,d,nx,ny,t,a);const r=maxR*Math.exp(-d*d*1.7)*Math.min(1,Math.max(0,blend))*scale;if(r*dpr<.5)continue;ctx.beginPath();ctx.arc(center+(ix-half)*spacing*scale,center+(iy-half)*spacing*scale,r,0,TAU);ctx.fill()}};const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce){draw(0,levelAt(0),SCALE[stateRef.current]);return}let t=0,a=0,scale=SCALE[stateRef.current],vel=0,last=performance.now(),raf=0;const frame=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;t+=dt;const cur=stateRef.current,target=levelAt(t),rate=target>a ? .22 : .08;a+=(target-a)*(1-Math.pow(1-rate,dt*60));const step=1-Math.pow(1-.16,dt*60);for(const s of STATES)weights[s]+=((s===cur?1:0)-weights[s])*step;vel+=(-180*(scale-SCALE[cur])-26*vel)*dt;scale+=vel*dt;draw(t,a,scale);raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return()=>cancelAnimationFrame(raf)},[size,color,dots,dpr]);return <div className={cn('flex flex-col items-center gap-3',className)} {...props}><canvas ref={ref} aria-hidden className="block" style={{width:size,height:size}}/><span className="orb-status" role="status" aria-live="polite">{labels?.[state]??({idle:'Idle',listening:'Listening',thinking:'Thinking'}[state])}</span></div>}
