"""harden concept prerequisite constraints

Revision ID: 62877ec06b96
Revises: 83afbf3f070b
Create Date: 2026-09-05 11:20:13.419362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62877ec06b96'
down_revision: Union[str, Sequence[str], None] = '83afbf3f070b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_concept_prerequisite', 'concept_prerequisites', ['concept_id', 'prerequisite_concept_id'])
    op.create_check_constraint('check_no_self_prerequisite', 'concept_prerequisites', 'concept_id != prerequisite_concept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_no_self_prerequisite', 'concept_prerequisites', type_='check')
    op.drop_constraint('uq_concept_prerequisite', 'concept_prerequisites', type_='unique')
    # ### end Alembic commands ###
