"""add revision state

Revision ID: 6d8d486e680b
Revises: f246985a1369
Create Date: 2026-09-17 15:43:01.256493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8d486e680b'
down_revision: Union[str, Sequence[str], None] = 'f246985a1369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('retrievability', sa.Float(), nullable=False),
    sa.Column('last_review_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('difficulty >= 0.0 AND difficulty <= 1.0', name='ck_revision_difficulty_range'),
    sa.CheckConstraint('retrievability >= 0.0 AND retrievability <= 1.0', name='ck_revision_retrievability_range'),
    sa.CheckConstraint('review_count >= 0', name='ck_revision_review_count_nonnegative'),
    sa.CheckConstraint('stability > 0', name='ck_revision_stability_positive'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_states_concept_id'), 'revision_states', ['concept_id'], unique=False)
    op.create_index(op.f('ix_revision_states_id'), 'revision_states', ['id'], unique=False)
    op.create_index(op.f('ix_revision_states_user_id'), 'revision_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revision_states_user_id'), table_name='revision_states')
    op.drop_index(op.f('ix_revision_states_id'), table_name='revision_states')
    op.drop_index(op.f('ix_revision_states_concept_id'), table_name='revision_states')
    op.drop_table('revision_states')
    # ### end Alembic commands ###
