"""add learner state uniqueness

Revision ID: 83afbf3f070b
Revises: ca6b1f579774
Create Date: 2026-09-05 10:53:35.855507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83afbf3f070b'
down_revision: Union[str, Sequence[str], None] = 'ca6b1f579774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_learner_state_user_concept', 'learner_states', ['user_id', 'concept_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_learner_state_user_concept', 'learner_states', type_='unique')
    # ### end Alembic commands ###
