"""add question difficulty constraint

Revision ID: c2aab4e078e6
Revises: a170d96e4e06
Create Date: 2026-09-02 22:08:55.137563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2aab4e078e6'
down_revision: Union[str, Sequence[str], None] = 'a170d96e4e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_question_difficulty', 'questions', 'difficulty BETWEEN 1 AND 5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_question_difficulty', 'questions', type_='check')
    # ### end Alembic commands ###
