"""add learner state model

Revision ID: d6d3d83072f7
Revises: e2e771283d68
Create Date: 2026-09-02 22:21:17.260781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d3d83072f7'
down_revision: Union[str, Sequence[str], None] = 'e2e771283d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempts_count >= 0', name='check_learner_state_attempts'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='check_learner_state_confidence'),
    sa.CheckConstraint('correct_count <= attempts_count', name='check_correct_not_exceed_attempts'),
    sa.CheckConstraint('correct_count >= 0', name='check_learner_state_correct'),
    sa.CheckConstraint('mastery BETWEEN 0 AND 1', name='check_learner_state_mastery'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_states')
    # ### end Alembic commands ###
