"""add attempt confidence constraint

Revision ID: e2e771283d68
Revises: c2aab4e078e6
Create Date: 2026-09-02 22:16:23.077791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e771283d68'
down_revision: Union[str, Sequence[str], None] = 'c2aab4e078e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_attempt_confidence', 'attempts', 'confidence IS NULL OR confidence BETWEEN 1 AND 5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_attempt_confidence', 'attempts', type_='check')
    # ### end Alembic commands ###
