"""add learner state history

Revision ID: f246985a1369
Revises: 62877ec06b96
Create Date: 2026-09-16 18:23:18.794086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f246985a1369'
down_revision: Union[str, Sequence[str], None] = '62877ec06b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempts_count >= 0', name='ck_history_attempts_nonnegative'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_history_confidence_range'),
    sa.CheckConstraint('correct_count <= attempts_count', name='ck_history_correct_lte_attempts'),
    sa.CheckConstraint('correct_count >= 0', name='ck_history_correct_nonnegative'),
    sa.CheckConstraint('mastery >= 0.0 AND mastery <= 1.0', name='ck_history_mastery_range'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_state_history_concept_id'), 'learner_state_history', ['concept_id'], unique=False)
    op.create_index(op.f('ix_learner_state_history_id'), 'learner_state_history', ['id'], unique=False)
    op.create_index(op.f('ix_learner_state_history_user_id'), 'learner_state_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_state_history_user_id'), table_name='learner_state_history')
    op.drop_index(op.f('ix_learner_state_history_id'), table_name='learner_state_history')
    op.drop_index(op.f('ix_learner_state_history_concept_id'), table_name='learner_state_history')
    op.drop_table('learner_state_history')
    # ### end Alembic commands ###
