import { Link, useNavigate } from 'react-router-dom'
import { Brain, Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import Logo from '../components/Logo'
import { Button } from '../components/UI'
import FluidOrb from '../components/animated/FluidOrb'

export function Login(){const nav=useNavigate();const [show,setShow]=useState(false);return <div className="auth-page"><div className="auth-glow"/><div className="auth-grid"><section className="auth-story"><Logo/><div className="auth-orb"><FluidOrb size={250} color="#6E5BFF"/></div><div className="story-copy"><span className="eyebrow">ADAPTIVE LEARNING ENVIRONMENT</span><h1>Learn at the edge of your <span>understanding.</span></h1><p>OpenTutor continuously models mastery, confidence, prerequisites, and revision needs to shape the next useful learning action.</p><div className="story-stats"><span><b>Bayesian</b><small>mastery model</small></span><span><b>Adaptive</b><small>next action</small></span><span><b>Contextual</b><small>AI tutor</small></span></div></div></section><section className="auth-card card"><div className="auth-head"><div className="auth-icon"><Brain size={20}/></div><div><span className="eyebrow">SECURE ACCESS</span><h2>Welcome back</h2></div></div><p className="muted">Continue your learning session.</p><form onSubmit={e=>{e.preventDefault();nav('/app/dashboard')}}><label>Email or username<input placeholder="you@example.com" defaultValue="student@opentutor.dev"/></label><label>Password<div className="password-wrap"><input type={show?'text':'password'} defaultValue="password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><div className="form-row"><label className="check"><input type="checkbox" defaultChecked/> <span>Remember me</span></label><a href="#">Forgot password?</a></div><Button>Sign In</Button></form><div className="auth-divider"><span>or</span></div><p className="auth-footer">Don't have an account? <Link to="/register">Create account</Link></p><div className="security-note"><ShieldCheck size={15}/> Demo authentication — production auth will be connected during integration.</div></section></div></div>}
export function Register(){const nav=useNavigate();return <div className="auth-page"><div className="auth-glow"/><div className="auth-card card register-card"><Logo/><div className="auth-head"><div><span className="eyebrow">BEGIN YOUR PATH</span><h2>Create your learner profile</h2></div></div><p className="muted">Your learner state will evolve as you study.</p><form onSubmit={e=>{e.preventDefault();nav('/app/dashboard')}}><div className="two-inputs"><label>Name<input placeholder="Your name"/></label><label>Username<input placeholder="username"/></label></div><label>Email<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="Create a password"/></label><Button>Create Account</Button></form><p className="auth-footer">Already have an account? <Link to="/login">Sign in</Link></p></div></div>}
